### ISSUE TITLE
dlib error messages on dub build

### ISSUE THREAD

**Issue by infinityplusb** [gecko0307/dlib#159]
I'm using dagon, which imports dlib as a prereq.
This works on one PC, but when I git cloned my repo to another computer to compile, it gives me the following errors. 

Are there prereqs for dlib that are documented somewhere?
```

brian@tonk:~/Documents/Programming/work/nab/ants$ dub
Performing "debug" build using /usr/bin/ldc2 for x86_64.
bindbc-loader 0.1.1: target for configuration "noBC" is up to date.
bindbc-ft 0.1.0: target for configuration "library" is up to date.
bindbc-nuklear 0.1.0: target for configuration "dynamic" is up to date.
bindbc-opengl 0.4.0: target for configuration "dynamic" is up to date.
bindbc-sdl 0.4.1: target for configuration "dynamic" is up to date.
dlib 0.16.0: building configuration "library"...
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/audio/unmanaged.d(68,41): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(UnmanagedGenericSound)(UnmanagedGenericSound), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/audio/unmanaged.d(73,41): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(UnmanagedGenericSound)(double, uint, uint, SampleFormat), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/audio/unmanaged.d(94,41): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(UnmanagedGenericSound)(ulong, ulong, double, uint, uint, uint, SampleFormat), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/container/dict.d(126,43): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(Dict!(Directory, string))(ubyte), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/filesystem/stdfs.d(271,5): Error: template instance dlib.container.dict.Dict!(Directory, string) error instantiating
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/container/dict.d(126,43): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(Dict!(JSONValue, string))(ubyte), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/serialization/json.d(164,20): Error: template instance dlib.container.dict.Dict!(JSONValue, string) error instantiating
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/container/dict.d(126,43): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(Dict!(string, string))(ubyte), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/serialization/xml.d(101,5): Error: template instance dlib.container.dict.Dict!(string, string) error instantiating
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/filesystem/stdfs.d(393,35): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(StdInFileStream)(shared(_IO_FILE)*), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/filesystem/stdfs.d(410,36): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(StdOutFileStream)(shared(_IO_FILE)*), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/filesystem/stdfs.d(427,31): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(StdIOStream)(shared(_IO_FILE)*), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/filesystem/stdfs.d(442,40): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(StdPosixDirectory)(string), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/filesystem/stdposixdir.d(168,47): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(StdPosixDirEntryRange)(DIR*), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/image/animation.d(257,52): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(UnmanagedAnimatedImage!cast(PixelFormat)0u)(uint, uint, uint), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/image/animation.d(259,53): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(UnmanagedAnimatedImage!cast(PixelFormat)4u)(uint, uint, uint), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/image/animation.d(264,53): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(UnmanagedAnimatedImage!cast(PixelFormat)1u)(uint, uint, uint), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/image/animation.d(266,54): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(UnmanagedAnimatedImage!cast(PixelFormat)5u)(uint, uint, uint), candidates are:
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(150,3):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == class))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(167,4):        dlib.core.memory.allocate(T, A...)(A args, string file = __FILE__, int line = __LINE__) if (is(T == struct))
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/core/memory.d(183,3):        dlib.core.memory.allocate(T)(size_t length, string file = __FILE__, int line = __LINE__) if (isArray!T)
/home/brian/.dub/packages/dlib-0.16.0/dlib/dlib/image/animation.d(271,54): Error: template dlib.core.memory.allocate cannot deduce function from argument types !(UnmanagedAnimatedImage!cast(PixelFormat)2u)(uint, uint, uint), candidates are:
/usr/bin/ldc2 failed with exit code 1.
```
I'm running Ubuntu 18.10, if that helps?

**Comment by gecko0307** [comment]
Which version of LDC are you using? Seems like a very old one that doesn't have [this feature](https://dlang.org/changelog/2.079.0.html#default_after_variadic). I recommend using DMD 2.085 or 2.086, LDC 1.14 or 1.15.

**Comment by infinityplusb** [comment]
Weirdly linux thinks it has the latest ldc ...  
```
brian@tonk:~/Documents/Programming/work/nab/ants$ sudo apt install ldc
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ldc is already the newest version (1:1.8.0-1).
```
I thought my dmd version was potentially too old, but it's not too bad.
```
brian@tonk:~/Documents/Programming/work/nab/ants$ dmd --version
DMD64 D Compiler v2.085.1
Copyright (C) 1999-2019 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

I've manually installed ldc 1.15 from [here](https://dlang.org/install.html) and that seems to work.

**Comment by gecko0307** [comment]
I've added fallback for old frontends, so now it should compile with ldc 1.8 as well
